require("lucas.plugin_config.telescope")
require("lucas.plugin_config.colors")
require("lucas.plugin_config.treesitter")
require("lucas.plugin_config.harpoon")
require("lucas.plugin_config.undotree")
require("lucas.plugin_config.fugitive")
